"""empty message

Revision ID: 14bea345ecc1
Revises: 
Create Date: 2018-08-08 08:43:21.172080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bea345ecc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('companyname', sa.VARCHAR(length=400), nullable=False),
    sa.Column('apkname', sa.VARCHAR(length=200), nullable=False),
    sa.Column('apkdetail', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('apkcompany', sa.TEXT(), nullable=False),
    sa.Column('companyRI', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apkname')
    )
    op.create_table('new',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('headline', sa.String(length=400), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('datetime', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('chose_sort', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['new.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('new')
    op.drop_table('apk')
    # ### end Alembic commands ###
