SECRET_KEY='a secret key'
DEBUG = True
HOSTNAME=''
PORT    =''
DATABASE=''
USERNAME=''
PASSWORD=''
SQLALCHEMY_TRACK_MODIFICATIONS=False
DB_URI  ='mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,
        HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI=DB_URI

MAIL_PATH = ''

